# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 09:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_reddit_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='article',
        ),
        migrations.AlterField(
            model_name='article',
            name='reddit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='web.Reddit'),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
